# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AstroBrowser' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AstroBrowser
  pod 'Alamofire', '~> 5.4'
  pod 'IGListKit', '~> 4.0.0'
  pod 'SDWebImage', '~> 5.0'

  target 'AstroBrowserTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AstroBrowserUITests' do
    # Pods for testing
  end

end
